version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shop"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: chien147/shop-backend:latest
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./streams:/app/streams
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/api/ac/info || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  app-network:
    driver: bridge