spring.application.name=Shop

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.show-actuator=false

management.endpoints.web.exposure.include=info
management.endpoints.web.exposure.exclude=health
management.endpoints.web.base-path=/ac
management.info.env.enabled=true
server.port=${PORT:8080}

spring.security.enabled=true

author.name=Chien

jwt.secret=${JWT_SECRET}

# Core PayOS credentials
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}


gemini.api-key=${GEMINI_API_KEY}
cohere.api-key=${COHERE_API_KEY}
# Logging level: DEBUG | INFO | NONE
payos.log-level=NONE

image.upload.dir=${IMAGE_UPLOAD_DIR:/app/uploads}
domain=${BASE_URL:https://anbato.site}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/shop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:shop}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:140704}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.jpa.hibernate.ddl-auto=update

spring.main.banner-mode=off
logging.level.root=info
spring.jpa.open-in-view=false
server.servlet.context-path=/api


server.forward-headers-strategy=framework

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_GOOGLE}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
